### ISSUE TITLE
Cannot find module './child/index'

### ISSUE THREAD

**Issue by CloudSurgeon** [delphix/dx-workshops#3]
On workshop boot, the jumpbox runs a script called provision.sh. This script builds and deploys web applications to the web servers. 

Occasionally, the ansible role that builds and deploys the web app will fail on the "BUILD HTML" step due to a failure in "INSTALL PACKAGES" to properly pull down packages.

The result is that the WAIT file will turn to ERROR with error messaging like the below in the log:

> fatal: [testweb]: FAILED! => {"attempts": 5, "changed": true, "cmd": ["/usr/local/lib/npm/bin/ng", "build", "--prod"], "delta": "0:00:02.927936", "end": "2019-09-18 05:34:46.951764", "msg": "non-zero return code", "rc": 1, "start": "2019-09-18 05:34:44.023828", "stderr": "Your global Angular CLI version (8.2.1) is greater than your local\nversion (6.1.5). The local Angular CLI version is used.\n\nTo disable this warning use \"ng config -g cli.warnings.versionMismatch false\".\nCannot find module './child/index'\nError: Cannot find module './child/index'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.resolve (internal/modules/cjs/helpers.js:33:19)\n    at Object.<anonymous> (/tmp/test/client/node_modules/worker-farm/lib/fork.js:4:30)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (/tmp/test/client/node_modules/worker-farm/lib/farm.js:15:33)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)", "stderr_lines": ["Your global Angular CLI version (8.2.1) is greater than your local", "version (6.1.5). The local Angular CLI version is used.", "", "To disable this warning use \"ng config -g cli.warnings.versionMismatch false\".", "Cannot find module './child/index'", "Error: Cannot find module './child/index'", "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)", "    at Function.resolve (internal/modules/cjs/helpers.js:33:19)", "    at Object.<anonymous> (/tmp/test/client/node_modules/worker-farm/lib/fork.js:4:30)", "    at Module._compile (internal/modules/cjs/loader.js:778:30)", "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)", "    at Module.load (internal/modules/cjs/loader.js:653:32)", "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)", "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)", "    at Module.require (internal/modules/cjs/loader.js:692:17)", "    at require (internal/modules/cjs/helpers.js:25:18)", "    at Object.<anonymous> (/tmp/test/client/node_modules/worker-farm/lib/farm.js:15:33)", "    at Module._compile (internal/modules/cjs/loader.js:778:30)", "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)", "    at Module.load (internal/modules/cjs/loader.js:653:32)", "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)", "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)"], "stdout": "", "stdout_lines": []}
> 
> PLAY RECAP *********************************************************************
> testweb                    : ok=15   changed=4    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
> 
> 3117
> It took 407 seconds to complete

**Comment by CloudSurgeon** [comment]
The issue causes a corruption in the modules and simplest workaround is to reboot the jumpbox, which will conduct a set of cleanup and environment preparation steps upon boot that should resolve the situation.

**Comment by CloudSurgeon** [comment]
Resolved here: ddc3fbe1c2aedfbfba17e7a0379dd2359e0fd7fa

**Comment by CloudSurgeon** [comment]
Will be resolved in v2.08

**Comment by CloudSurgeon** [comment]
resolved in #4
